# Generated by Django 5.1.2 on 2024-10-29 19:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LasttName', models.CharField(max_length=30)),
                ('PhoneNumber', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prodocts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Picture', models.ImageField(upload_to='upload/product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('address', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(max_length=13)),
                ('OrderDate', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.prodocts')),
            ],
        ),
    ]
