# Generated by Django 5.1.2 on 2024-10-31 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_prodocts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodocts',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
