# Generated by Django 5.1.2 on 2024-10-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_prodocts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodocts',
            name='Brand',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prodocts',
            name='QuantityInStock',
            field=models.IntegerField(default=0),
        ),
    ]
