# Generated by Django 5.1.2 on 2024-10-31 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_prodocts_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodocts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
