# Generated by Django 5.1.2 on 2024-10-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_brand_remove_prodocts_brand_prodocts_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='Brandname',
        ),
    ]
